title: <p align="center"> Sunkanna Basa </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/sunkanna-basa">LinkedIn</a> |
  <a href="https://github.com/Sun0023">GitHub</a>
  
  <br>   
  Basically an engineering grad-turned-writer. And I am turning back to engineering through Machine Learning Engineering.
  <br>
  </p>



theme: jekyll-theme-minimal
