title: <p align="center"> Sunkanna Basa </p>
logo: /assets/6732a05f-132f-40bb-b959-ab1f5b931b36.jpg

description:
  <p align="center">
  <a href="https://github.com/Sun0023">GitHub</a>
  
  <br>   
  Working a writer as of now. But I am much into Machine Learning from now onwards.
  <br>
  </p>



theme: jekyll-theme-minimal
